// 美术馆（Akari）— generated wall layouts with verified lighting solutions.
registerGame('akari', openAkari);
const AKARI_LEVELS={easy:{name:'入门',n:5,walls:.18,numbers:1},medium:{name:'标准',n:6,walls:.2,numbers:.85},hard:{name:'进阶',n:7,walls:.22,numbers:.7},expert:{name:'困难',n:8,walls:.24,numbers:.58},master:{name:'大师',n:9,walls:.26,numbers:.48}};let akariNonce=0;
function akariRay(index,walls,n){const r=Math.floor(index/n),c=index%n,out=[index];for(const [dr,dc] of [[-1,0],[1,0],[0,-1],[0,1]])for(let rr=r+dr,cc=c+dc;rr>=0&&rr<n&&cc>=0&&cc<n;rr+=dr,cc+=dc){const i=rr*n+cc;if(walls.has(i))break;out.push(i);}return out;}
function akariConflict(index,bulbs,walls,n){return akariRay(index,walls,n).some(i=>i!==index&&bulbs.has(i));}
function solveAkariLayout(n,walls,nodeLimit=120000){const white=[...Array(n*n)].map((_,i)=>i).filter(i=>!walls.has(i)),rays=new Map(white.map(i=>[i,akariRay(i,walls,n)])),bulbs=new Set();let nodes=0;function search(){if(++nodes>nodeLimit)return false;const unlit=white.find(cell=>![...bulbs].some(b=>rays.get(b).includes(cell)));if(unlit==null)return true;const candidates=rays.get(unlit).filter(cell=>!akariConflict(cell,bulbs,walls,n)).sort((a,b)=>rays.get(b).length-rays.get(a).length);for(const cell of candidates){bulbs.add(cell);if(search())return true;bulbs.delete(cell);}return false;}return search()?{bulbs:new Set(bulbs),nodes}:null;}
function akariAdjacent(index,n){const r=Math.floor(index/n),c=index%n;return[[-1,0],[1,0],[0,-1],[0,1]].map(([dr,dc])=>[r+dr,c+dc]).filter(([rr,cc])=>rr>=0&&rr<n&&cc>=0&&cc<n).map(([rr,cc])=>rr*n+cc);}
function generateAkari(difficulty,providedRandom=null,testMode=false){const cfg=AKARI_LEVELS[difficulty],random=providedRandom||seededRandom((Date.now()+ ++akariNonce*141650963)>>>0);for(let attempt=0;attempt<160;attempt++){const walls=new Set();for(let i=0;i<cfg.n*cfg.n;i++)if(random()<cfg.walls)walls.add(i);if(walls.size<2||walls.size>cfg.n*cfg.n*.4)continue;const solved=solveAkariLayout(cfg.n,walls);if(!solved||solved.bulbs.size<2)continue;const clues=new Map();walls.forEach(i=>{if(random()<=cfg.numbers)clues.set(i,akariAdjacent(i,cfg.n).filter(x=>solved.bulbs.has(x)).length);});const signature=`${cfg.n}:${[...walls].join('.')}:${[...solved.bulbs].join('.')}:${[...clues].join('.')}`;if(!testMode){if(progress.seen.akari.includes(signature))continue;progress.seen.akari=[signature,...progress.seen.akari].slice(0,80);saveProgress();}return{difficulty,...cfg,walls,solution:solved.bulbs,clues,signature};}throw new Error('暂时无法生成可解美术馆关卡');}
function akariValid(p,marks){const bulbs=new Set(marks.map((v,i)=>v===1?i:-1).filter(i=>i>=0));for(const bulb of bulbs)if(akariConflict(bulb,new Set([...bulbs].filter(x=>x!==bulb)),p.walls,p.n))return false;for(let i=0;i<p.n*p.n;i++)if(!p.walls.has(i)&&![...bulbs].some(b=>akariRay(b,p.walls,p.n).includes(i)))return false;for(const [wall,clue] of p.clues)if(akariAdjacent(wall,p.n).filter(i=>bulbs.has(i)).length!==clue)return false;return true;}
function openAkari(){state={kind:'akari-menu'};prepareGeneric('美术馆');stage.innerHTML=`<div class="stage-inner"><p class="eyebrow">照明推理 · 视线约束</p><h2>选择美术馆难度</h2><p>放置灯泡照亮所有白格；灯泡不能互相照见，数字墙表示相邻灯泡数量。</p><div class="choice-grid">${Object.entries(AKARI_LEVELS).map(([id,l])=>`<button class="choice" data-akari="${id}"><b>${l.name}</b><br><small>${l.n}×${l.n} · ${Math.round(l.numbers*100)}% 数字墙</small></button>`).join('')}</div></div>`;stage.querySelector('.choice-grid').onclick=e=>{const b=e.target.closest('[data-akari]');if(b)startAkari(b.dataset.akari);};}
function startAkari(difficulty){prepareGeneric('正在生成可解关卡…');let p;try{p=generateAkari(difficulty);}catch(e){toast(e.message);return openAkari();}state={kind:'akari',...p,marks:Array(p.n*p.n).fill(0),tool:1,history:[],hints:0,mistakes:0,startedAt:Date.now(),feedback:'放灯照亮全部白格，× 可标记不能放灯处'};renderAkari();}
function renderAkari(){stage.className='game-stage akari-stage';const bulbs=new Set(state.marks.map((v,i)=>v===1?i:-1).filter(i=>i>=0)),lit=new Set();bulbs.forEach(b=>akariRay(b,state.walls,state.n).forEach(i=>lit.add(i)));document.getElementById('lives').textContent=`${AKARI_LEVELS[state.difficulty].name} · 灯泡 ${bulbs.size}`;document.getElementById('level').textContent=`照亮 ${[...lit].filter(i=>!state.walls.has(i)).length}/${state.n*state.n-state.walls.size}`;stage.innerHTML=`<div class="stage-inner"><h2>美术馆</h2><p class="muted">${state.feedback}</p><div class="akari-board" style="--akari-n:${state.n}">${state.marks.map((v,i)=>state.walls.has(i)?`<div class="akari-cell wall">${state.clues.has(i)?state.clues.get(i):''}</div>`:`<button class="akari-cell ${lit.has(i)?'lit':''} ${v===1?'bulb':''} ${v===2?'crossed':''}" data-akari-cell="${i}">${v===1?'●':v===2?'×':''}</button>`).join('')}</div><div class="puzzle-toolbar"><button class="btn btn-secondary ${state.tool===1?'active':''}" data-akari-tool="1">● 灯泡</button><button class="btn btn-secondary ${state.tool===2?'active':''}" data-akari-tool="2">× 排除</button><button class="btn btn-secondary" id="undoAkari">撤销</button><button class="btn btn-secondary" id="checkAkari">查错</button><button class="btn btn-secondary" id="hintAkari">AI 一步 · 25 XP</button><button class="btn btn-secondary" id="newAkari">换题</button><button class="btn btn-secondary" id="closeAkari">主页</button></div></div>`;stage.querySelector('.akari-board').onclick=e=>{const b=e.target.closest('[data-akari-cell]');if(b)markAkari(+b.dataset.akariCell);};stage.querySelectorAll('[data-akari-tool]').forEach(b=>b.onclick=()=>{state.tool=+b.dataset.akariTool;renderAkari();});document.getElementById('undoAkari').onclick=()=>{const p=state.history.pop();if(!p)return toast('还没有可撤销的操作');state.marks=p;renderAkari();};document.getElementById('checkAkari').onclick=checkAkari;document.getElementById('hintAkari').onclick=hintAkari;document.getElementById('newAkari').onclick=()=>startAkari(state.difficulty);document.getElementById('closeAkari').onclick=closeGame;}
function markAkari(index){state.history.push([...state.marks]);state.marks[index]=state.marks[index]===state.tool?0:state.tool;if(akariValid(state,state.marks))return renderAkari(),setTimeout(finishAkari,250);renderAkari();}
function checkAkari(){const wrong=state.marks.filter((v,i)=>v===1&&!state.solution.has(i)).length;state.mistakes+=!!wrong;state.feedback=wrong?`有 ${wrong} 个灯泡位置不正确`:'当前灯泡位置均可成立';renderAkari();}
function hintAkari(){if(progress.xp<25)return toast('积分不足');let index=state.marks.findIndex((v,i)=>v===1&&!state.solution.has(i)),target=2;if(index<0){index=[...state.solution].find(i=>state.marks[i]!==1);target=1;}if(index==null||index<0)return toast('已经完成');state.history.push([...state.marks]);state.marks[index]=target;state.hints++;progress.xp-=25;saveProgress();state.feedback=target===1?'AI 已放置一个确定灯泡':'AI 已排除一个错误灯位';if(akariValid(state,state.marks))return renderAkari(),setTimeout(finishAkari,250);renderAkari();}
function finishAkari(){if(state.kind!=='akari')return;const sec=Math.max(1,Math.round((Date.now()-state.startedAt)/1000)),d=state.difficulty;completeGame('akari','美术馆',730+state.n*35-state.hints*40-state.mistakes*30-sec,[{value:`${state.n}×${state.n}`,label:'棋盘'},{value:state.hints,label:'辅助'},{value:`${sec}s`,label:'用时'}],()=>startAkari(d));}
