// 城堡拼图 — loaded as a classic script to support file:// usage.
registerGame('castle', openCastlePuzzle);
function normalizeShape(cells){const minX=Math.min(...cells.map(c=>c[0])),minY=Math.min(...cells.map(c=>c[1]));return cells.map(([x,y])=>[x-minX,y-minY]).sort((a,b)=>a[1]-b[1]||a[0]-b[0]);}
let castleGenerationNonce=0;
function rotateShape(cells){return normalizeShape(cells.map(([x,y])=>[-y,x]));}
function shapeOrientations(cells){const out=[],seen=new Set();let shape=normalizeShape(cells);for(let i=0;i<4;i++){const key=shape.map(c=>c.join(',')).join(';');if(!seen.has(key)){seen.add(key);out.push(shape);}shape=rotateShape(shape);}return out;}
function castleMask(width,height){return [...Array(width*height)].map((_,i)=>i);}
function growCastleRegions(width,mask,sizes,random){const labels=new Map(),seeds=shuffle(mask,random).slice(0,sizes.length),counts=Array(sizes.length).fill(1);seeds.forEach((cell,i)=>labels.set(cell,i));while(labels.size<mask.length){const choices=[];for(const cell of mask)if(!labels.has(cell)){const possible=[cell-1,cell+1,cell-width,cell+width].filter(n=>labels.has(n)&&Math.abs(n%width-cell%width)+Math.abs(Math.floor(n/width)-Math.floor(cell/width))===1&&counts[labels.get(n)]<sizes[labels.get(n)]);for(const n of possible)choices.push({cell,label:labels.get(n)});}if(!choices.length)return null;const pick=choices[Math.floor(random()*choices.length)];labels.set(pick.cell,pick.label);counts[pick.label]++;}if(counts.some((n,i)=>n!==sizes[i]))return null;const regions=sizes.map(()=>[]);for(const [cell,label] of labels)regions[label].push([cell%width,Math.floor(cell/width)]);return regions.map(normalizeShape);}
function castlePlacements(width,height,mask,pieces){const allowed=new Set(mask),out=[];pieces.forEach((shape,pieceId)=>{const pieceWidth=Math.max(...shape.map(c=>c[0]))+1,pieceHeight=Math.max(...shape.map(c=>c[1]))+1;for(let y=0;y<=height-pieceHeight;y++)for(let x=0;x<=width-pieceWidth;x++){const cells=shape.map(([dx,dy])=>(y+dy)*width+x+dx);if(cells.every(c=>allowed.has(c)))out.push({pieceId,x,y,cells});}});return out;}
function solveCastle(width,height,mask,pieces,limit=2){const placements=castlePlacements(width,height,mask,pieces),byCell=new Map(mask.map(c=>[c,placements.filter(p=>p.cells.includes(c))]));let count=0,solution=null;const used=new Set(),filled=new Set(),chosen=[];function search(){if(count>=limit)return;if(filled.size===mask.length){count++;if(!solution)solution=chosen.map(p=>({...p,cells:[...p.cells]}));return;}let options=null;for(const c of mask)if(!filled.has(c)){const list=byCell.get(c).filter(p=>!used.has(p.pieceId)&&p.cells.every(x=>!filled.has(x)));if(!options||list.length<options.length){options=list;if(!list.length)return;}}for(const p of options){used.add(p.pieceId);p.cells.forEach(c=>filled.add(c));chosen.push(p);search();chosen.pop();p.cells.forEach(c=>filled.delete(c));used.delete(p.pieceId);if(count>=limit)return;}}search();return{count,solution};}
function generateCastlePuzzle(difficulty){const config={easy:[4,4,[3,3,4,6]],medium:[5,5,[3,4,5,6,7]],hard:[6,5,[3,4,4,5,6,8]]}[difficulty],[width,height,sizes]=config,mask=castleMask(width,height),nonce=++castleGenerationNonce,base=Date.now()+nonce*104729;for(let attempt=0;attempt<6000;attempt++){const random=seededRandom((base+attempt*7919)>>>0),pieces=growCastleRegions(width,mask,shuffle(sizes,random),random);if(!pieces)continue;const solved=solveCastle(width,height,mask,pieces,2);if(solved.count!==1)continue;const signature=`${difficulty}:${pieces.map(p=>p.map(c=>c.join(',')).join('.')).join('|')}`;if(progress.seen.castle.includes(signature))continue;progress.seen.castle=[signature,...progress.seen.castle].slice(0,60);saveProgress();return{difficulty,width,height,mask,pieces,solution:solved.solution,signature};}throw new Error('无法生成唯一解城堡，请重新尝试');}
function openCastlePuzzle(){state={kind:'castle-menu',timer:null};prepareGeneric('城堡拼图');stage.innerHTML=`<div class="stage-inner"><p class="eyebrow">三轮地图拼合</p><h2>选择城堡难度</h2><p>拖动固定方向的地图拼块，填满上方矩形区域。</p><div class="choice-grid"><button class="choice" data-castle="easy">初级 · 4×4</button><button class="choice" data-castle="medium">中级 · 5×5</button><button class="choice" data-castle="hard">困难 · 6×5</button></div></div>`;stage.querySelector('.choice-grid').addEventListener('click',e=>{const b=e.target.closest('[data-castle]');if(b)startCastlePuzzle(b.dataset.castle);});}
function startCastlePuzzle(difficulty){startCastleRound(difficulty,1,Date.now(),0,0);}
function startCastleRound(difficulty,round,sessionStarted,totalMoves,hints){document.getElementById('lives').textContent='正在生成唯一解…';const puzzle=generateCastlePuzzle(difficulty);state={kind:'castle',...puzzle,round,sessionStarted,totalMoves,hints,selected:0,dragging:null,placed:new Map(),moves:0,timer:null};renderCastlePuzzle();}
function castlePieceMarkup(piece,id){const width=Math.max(...piece.map(c=>c[0]))+1,height=Math.max(...piece.map(c=>c[1]))+1,cells=new Set(piece.map(c=>c.join(',')));return `<div class="piece-map ${state.selected===id?'selected':''} ${state.placed.has(id)?'placed':''}" data-piece="${id}" style="grid-template-columns:repeat(${width},22px)" role="button" aria-label="地图拼块 ${id+1}">${[...Array(width*height)].map((_,i)=>`<span class="${cells.has(`${i%width},${Math.floor(i/width)}`)?`terrain-${id%5}`:'empty'}"></span>`).join('')}</div>`;}
function renderCastlePuzzle(message='拖动下方地图拼块到网格'){stage.className='game-stage castle-stage';const filled=new Map();for(const [id,p] of state.placed)for(const cell of p.cells)filled.set(cell,id);const incorrect=castleIncorrectPieces(),autoCost=Math.max(80,incorrect.length*35);document.getElementById('lives').textContent=`${state.round}/3 · 已放 ${state.placed.size}/${state.pieces.length}`;document.getElementById('level').textContent=`${state.width}×${state.height}`;stage.innerHTML=`<div class="stage-inner"><h2>城堡拼图</h2><p class="muted">${message}</p><div class="castle-playfield"><div class="castle-board" style="--castle-height:${state.height};--castle-ratio:${state.width/state.height};grid-template-columns:repeat(${state.width},1fr)">${state.mask.map(cell=>`<button class="castle-cell ${filled.has(cell)?`filled terrain-${filled.get(cell)%5}`:''}" data-castle-cell="${cell}" aria-label="网格 ${cell+1}"></button>`).join('')}</div></div><div class="castle-toolbar"><button class="btn btn-secondary" id="hintCastle">AI 智能一步 · 40 XP</button><button class="btn btn-secondary" id="solveCastleRound">AI 完成本轮 · ${autoCost} XP</button><button class="btn btn-secondary" id="newCastle">换一题</button><button class="btn btn-secondary" id="closeCastle">返回主页</button></div><div class="piece-water"><div class="piece-tray">${state.pieces.map(castlePieceMarkup).join('')}</div></div></div>`;
  const tray=stage.querySelector('.piece-tray'),board=stage.querySelector('.castle-board');tray.addEventListener('pointerdown',e=>{const piece=e.target.closest('[data-piece]');if(!piece)return;state.selected=Number(piece.dataset.piece);state.dragging=state.selected;tray.querySelectorAll('.piece-map').forEach(p=>p.classList.toggle('selected',Number(p.dataset.piece)===state.selected));});tray.addEventListener('click',e=>{const piece=e.target.closest('[data-piece]');if(piece)state.selected=Number(piece.dataset.piece);});board.addEventListener('pointerup',e=>{if(state.dragging===null)return;const cell=(e.target.closest('[data-castle-cell]')||document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-castle-cell]'));state.dragging=null;if(cell){state.suppressCastleClick=true;placeCastlePiece(Number(cell.dataset.castleCell));setTimeout(()=>state.suppressCastleClick=false,0);}});board.addEventListener('click',e=>{if(state.suppressCastleClick)return;const cell=e.target.closest('[data-castle-cell]');if(!cell)return;const index=Number(cell.dataset.castleCell);if(filled.has(index)){state.placed.delete(filled.get(index));return renderCastlePuzzle('已将拼块放回水面');}placeCastlePiece(index);});document.getElementById('hintCastle').addEventListener('click',hintCastlePuzzle);document.getElementById('solveCastleRound').addEventListener('click',solveCastleRoundWithAI);document.getElementById('newCastle').addEventListener('click',()=>startCastleRound(state.difficulty,state.round,state.sessionStarted,state.totalMoves,state.hints));document.getElementById('closeCastle').addEventListener('click',closeGame);}
function placeCastlePiece(targetCell){const id=state.selected;if(state.placed.has(id))return;const occupied=new Set([...state.placed.values()].flatMap(p=>p.cells)),candidates=castlePlacements(state.width,state.height,state.mask,state.pieces).filter(p=>p.pieceId===id&&p.cells.every(c=>!occupied.has(c))),containing=candidates.filter(p=>p.cells.includes(targetCell)),placement=(containing.length?containing:candidates).sort((a,b)=>Math.abs(a.x-targetCell%state.width)+Math.abs(a.y-Math.floor(targetCell/state.width))-Math.abs(b.x-targetCell%state.width)-Math.abs(b.y-Math.floor(targetCell/state.width)))[0];if(!placement)return renderCastlePuzzle('剩余空间放不下这块地图');state.placed.set(id,{cells:[...placement.cells]});state.moves++;state.totalMoves++;if(state.placed.size===state.pieces.length)return finishCastleRound();state.selected=state.pieces.findIndex((_,i)=>!state.placed.has(i));renderCastlePuzzle();}
function finishCastleRound(){if(state.round<3){const {difficulty,round,sessionStarted,totalMoves,hints}=state;toast(`第 ${round} 轮完成`);return state.timer=setTimeout(()=>startCastleRound(difficulty,round+1,sessionStarted,totalMoves,hints),650);}const seconds=Math.round((Date.now()-state.sessionStarted)/1000);completeGame('castle','城堡拼图',Math.max(100,2997-state.totalMoves*8-state.hints*50-seconds*2)/3,[{value:'3/3',label:'完成轮次'},{value:state.totalMoves,label:'摆放'},{value:`${seconds}s`,label:'总用时'}],()=>startCastlePuzzle(state.difficulty));}
function sameCastleCells(a,b){return a&&[...a].sort((x,y)=>x-y).join(',')===[...b].sort((x,y)=>x-y).join(',');}
function castleIncorrectPieces(){return state.solution.filter(target=>!sameCastleCells(state.placed.get(target.pieceId)?.cells,target.cells));}
function hintCastlePuzzle(){if(progress.xp<40)return toast('积分不足');const target=castleIncorrectPieces()[0];if(!target)return toast('当前摆法已经正确');state.placed.delete(target.pieceId);for(const [id,p] of [...state.placed])if(p.cells.some(c=>target.cells.includes(c)))state.placed.delete(id);state.placed.set(target.pieceId,{cells:[...target.cells]});progress.xp-=40;state.hints++;saveProgress();state.selected=state.pieces.findIndex((_,i)=>!state.placed.has(i));if(state.placed.size===state.pieces.length&&!castleIncorrectPieces().length)return finishCastleRound();renderCastlePuzzle(`AI 已校正地图拼块 ${target.pieceId+1}`);}
function solveCastleRoundWithAI(){const incorrect=castleIncorrectPieces(),cost=Math.max(80,incorrect.length*35);if(!incorrect.length)return finishCastleRound();if(progress.xp<cost)return toast(`积分不足，需要 ${cost} XP`);progress.xp-=cost;state.hints+=incorrect.length;state.placed.clear();state.solution.forEach(target=>state.placed.set(target.pieceId,{cells:[...target.cells]}));saveProgress();renderCastlePuzzle('AI 正在完成本轮…');state.timer=setTimeout(finishCastleRound,450);}
