// 数桥（Hashi）— connected bridge puzzles with solver-trivial tree layouts.
registerGame('hashi', openHashi);
const HASHI_LEVELS={easy:{name:'入门',islands:6},medium:{name:'标准',islands:8},hard:{name:'进阶',islands:10},expert:{name:'困难',islands:12},master:{name:'大师',islands:14}};
let hashiNonce=0;
function generateHashi(difficulty,providedRandom=null,testMode=false){const cfg=HASHI_LEVELS[difficulty],random=providedRandom||seededRandom((Date.now()+ ++hashiNonce*67867967)>>>0),raw=[];let r=0,c=0;raw.push({r,c});for(let i=1;i<cfg.islands;i++){i%2?c++:r++;raw.push({r,c});}const max=Math.max(...raw.flatMap(p=>[p.r,p.c])),flip=random()<.5,mirrorR=random()<.5,mirrorC=random()<.5,islands=raw.map((p,id)=>{let row=flip?p.c:p.r,col=flip?p.r:p.c;if(mirrorR)row=max-row;if(mirrorC)col=max-col;return{id,row,col,clue:0};}),edges=[];for(let i=0;i<islands.length-1;i++){const weight=random()<.32?2:1;edges.push({a:i,b:i+1,weight});islands[i].clue+=weight;islands[i+1].clue+=weight;}const signature=islands.map(p=>`${p.row}${p.col}${p.clue}`).join('-');if(!testMode){if(progress.seen.hashi.includes(signature))return generateHashi(difficulty,null,false);progress.seen.hashi=[signature,...progress.seen.hashi].slice(0,80);saveProgress();}return{difficulty,...cfg,grid:max+1,islands,edges,signature};}
function hashiConnected(puzzle,values){const seen=new Set([0]),stack=[0];while(stack.length){const node=stack.pop();puzzle.edges.forEach((edge,i)=>{if(!values[i])return;const next=edge.a===node?edge.b:edge.b===node?edge.a:null;if(next!=null&&!seen.has(next)){seen.add(next);stack.push(next);}});}return seen.size===puzzle.islands.length;}
function hashiValid(puzzle,values){return puzzle.islands.every(island=>puzzle.edges.reduce((sum,edge,i)=>sum+(edge.a===island.id||edge.b===island.id?values[i]:0),0)===island.clue)&&hashiConnected(puzzle,values);}
function openHashi(){state={kind:'hashi-menu'};prepareGeneric('数桥');stage.innerHTML=`<div class="stage-inner"><p class="eyebrow">连通推理 · 桥数约束</p><h2>选择数桥难度</h2><p>横向或纵向连接岛屿，每对岛最多两座桥，所有岛最终必须连通。</p><div class="choice-grid">${Object.entries(HASHI_LEVELS).map(([id,l])=>`<button class="choice" data-hashi="${id}"><b>${l.name}</b><br><small>${l.islands} 座岛</small></button>`).join('')}</div></div>`;stage.querySelector('.choice-grid').onclick=e=>{const b=e.target.closest('[data-hashi]');if(b)startHashi(b.dataset.hashi);};}
function startHashi(difficulty){const puzzle=generateHashi(difficulty);state={kind:'hashi',...puzzle,values:Array(puzzle.edges.length).fill(0),selected:null,history:[],hints:0,mistakes:0,startedAt:Date.now(),feedback:'依次点击两座相邻岛屿来架桥'};renderHashi();}
function renderHashi(){stage.className='game-stage hashi-stage';const done=state.values.filter(Boolean).length;document.getElementById('lives').textContent=`${HASHI_LEVELS[state.difficulty].name} · 桥段 ${done}/${state.edges.length}`;document.getElementById('level').textContent=`${state.islands.length} 座岛`;const pos=id=>state.islands[id];stage.innerHTML=`<div class="stage-inner"><h2>数桥</h2><p class="muted">${state.feedback}</p><div class="hashi-board" style="--hashi-grid:${state.grid}"><svg viewBox="0 0 ${state.grid-1} ${state.grid-1}" preserveAspectRatio="none">${state.edges.map((edge,i)=>{const a=pos(edge.a),b=pos(edge.b),v=state.values[i],offset=v===2?.07:0,horizontal=a.row===b.row,ox=horizontal?0:offset,oy=horizontal?offset:0;return`<line x1="${a.col-ox}" y1="${a.row-oy}" x2="${b.col-ox}" y2="${b.row-oy}" class="hashi-line ${v?'active':''}"/><line x1="${a.col+ox}" y1="${a.row+oy}" x2="${b.col+ox}" y2="${b.row+oy}" class="hashi-line ${v===2?'active':'ghost'}"/>`;}).join('')}</svg>${state.islands.map(p=>`<button class="hashi-island ${state.selected===p.id?'selected':''}" data-island="${p.id}" style="--r:${p.row};--c:${p.col}">${p.clue}</button>`).join('')}</div><div class="puzzle-toolbar"><button class="btn btn-secondary" id="undoHashi">撤销</button><button class="btn btn-secondary" id="checkHashi">查错</button><button class="btn btn-secondary" id="hintHashi">AI 一步 · 30 XP</button><button class="btn btn-secondary" id="newHashi">换题</button><button class="btn btn-secondary" id="closeHashi">主页</button></div></div>`;stage.querySelector('.hashi-board').onclick=e=>{const b=e.target.closest('[data-island]');if(b)selectHashi(Number(b.dataset.island));};document.getElementById('undoHashi').onclick=()=>{const prev=state.history.pop();if(!prev)return toast('还没有可撤销的操作');state.values=prev;state.feedback='已撤销';renderHashi();};document.getElementById('checkHashi').onclick=()=>{const wrong=state.values.filter((v,i)=>v!==state.edges[i].weight).length;state.mistakes+=!!wrong;state.feedback=wrong?`还有 ${wrong} 条桥不正确`:'当前桥梁全部正确';renderHashi();};document.getElementById('hintHashi').onclick=hintHashi;document.getElementById('newHashi').onclick=()=>startHashi(state.difficulty);document.getElementById('closeHashi').onclick=closeGame;}
function selectHashi(id){if(state.selected==null){state.selected=id;state.feedback='再选择同一直线上的相邻岛屿';return renderHashi();}if(state.selected===id){state.selected=null;return renderHashi();}const edgeIndex=state.edges.findIndex(e=>(e.a===state.selected&&e.b===id)||(e.b===state.selected&&e.a===id));if(edgeIndex<0){state.selected=id;state.feedback='这两座岛之间不能直接架桥';return renderHashi();}state.history.push([...state.values]);state.values[edgeIndex]=(state.values[edgeIndex]+1)%3;state.selected=null;state.feedback='点击同一对岛屿可切换单桥、双桥和无桥';if(hashiValid(state,state.values))return renderHashi(),setTimeout(finishHashi,250);renderHashi();}
function hintHashi(){if(progress.xp<30)return toast('积分不足');const i=state.values.findIndex((v,index)=>v!==state.edges[index].weight);if(i<0)return toast('已经完成');state.history.push([...state.values]);state.values[i]=state.edges[i].weight;state.hints++;progress.xp-=30;saveProgress();state.feedback='AI 已完成一条确定桥梁';if(hashiValid(state,state.values))return renderHashi(),setTimeout(finishHashi,250);renderHashi();}
function finishHashi(){if(state.kind!=='hashi')return;const sec=Math.max(1,Math.round((Date.now()-state.startedAt)/1000)),d=state.difficulty;completeGame('hashi','数桥',760+state.islands.length*15-state.hints*45-state.mistakes*30-sec,[{value:state.islands.length,label:'岛屿'},{value:state.hints,label:'辅助'},{value:`${sec}s`,label:'用时'}],()=>startHashi(d));}
