// 开关灯 — solvable procedural Lights Out puzzles.
registerGame('lights-out', openLightsOut);

const LIGHTS_LEVELS = {
  easy: { name:'入门', size:3, min:2, max:4 },
  medium: { name:'标准', size:4, min:4, max:8 },
  hard: { name:'进阶', size:5, min:7, max:13 },
  expert: { name:'困难', size:6, min:10, max:18 },
  master: { name:'大师', size:7, min:14, max:25 }
};
let lightsGenerationNonce=0;

function lightsAffected(index,size){const row=Math.floor(index/size),col=index%size,out=[index];if(row>0)out.push(index-size);if(row<size-1)out.push(index+size);if(col>0)out.push(index-1);if(col<size-1)out.push(index+1);return out;}
function toggleLights(board,size,index){const next=[...board];lightsAffected(index,size).forEach(cell=>next[cell]=next[cell]?0:1);return next;}
function applyLightPresses(board,size,presses){return presses.reduce((current,index)=>toggleLights(current,size,index),[...board]);}
function solveLightsOut(board,size){let best=null;for(let firstMask=0;firstMask<(1<<size);firstMask++){let work=[...board];const presses=[];for(let col=0;col<size;col++)if(firstMask&(1<<col)){presses.push(col);work=toggleLights(work,size,col);}for(let row=1;row<size;row++)for(let col=0;col<size;col++)if(work[(row-1)*size+col]){const index=row*size+col;presses.push(index);work=toggleLights(work,size,index);}if(work.every(value=>value===0)&&(!best||presses.length<best.length))best=presses;}return best;}
function generateLightsOut(difficulty){const config=LIGHTS_LEVELS[difficulty],nonce=++lightsGenerationNonce,base=Date.now()+nonce*32452843,total=config.size*config.size;for(let attempt=0;attempt<1600;attempt++){const random=seededRandom((base+attempt*65537)>>>0),pressCount=config.min+Math.floor(random()*(config.max-config.min+6)),presses=shuffle([...Array(total)].map((_,i)=>i),random).slice(0,Math.min(total,pressCount));const board=applyLightPresses(Array(total).fill(0),config.size,presses),solution=solveLightsOut(board,config.size);if(!solution||solution.length<config.min||solution.length>config.max)continue;const signature=`${config.size}:${board.join('')}`;if(progress.seen.lightsOut.includes(signature))continue;progress.seen.lightsOut=[signature,...progress.seen.lightsOut].slice(0,80);saveProgress();return{difficulty,...config,board,solution,signature};}throw new Error('暂时无法生成符合难度的开关灯关卡，请重试');}

function openLightsOut(){state={kind:'lights-menu',timer:null};prepareGeneric('开关灯');stage.innerHTML=`<div class="stage-inner"><p class="eyebrow">状态推理 · 最短解验证</p><h2>选择开关灯难度</h2><p>点击一盏灯会同时切换它自己及上下左右，目标是关闭全部灯。</p><div class="choice-grid">${Object.entries(LIGHTS_LEVELS).map(([id,level])=>`<button class="choice" data-lights-level="${id}"><b>${level.name} · ${level.size}×${level.size}</b><br><small>最短约 ${level.min}–${level.max} 步</small></button>`).join('')}</div><button class="btn btn-secondary" id="lightsTutorial" style="margin-top:12px">玩法教程</button></div>`;stage.querySelector('.choice-grid').addEventListener('click',event=>{const button=event.target.closest('[data-lights-level]');if(button)startLightsOut(button.dataset.lightsLevel);});document.getElementById('lightsTutorial').addEventListener('click',showLightsTutorial);}
function showLightsTutorial(){stage.innerHTML=`<div class="stage-inner"><p class="eyebrow">开关灯教程</p><h2>一次点击，切换一个十字</h2><p>点击任意格，它自身以及紧邻的上、下、左、右都会改变亮灭状态。角落影响 3 格，边缘影响 4 格，中间影响 5 格。</p><div class="lights-demo"><span></span><b>✦</b><span></span><b>✦</b><b>●</b><b>✦</b><span></span><b>✦</b><span></span></div><p class="muted">黑点是点击位置，星光是同时受到影响的格子。</p><button class="btn btn-primary" id="lightsTutorialDone">从 3×3 开始</button></div>`;document.getElementById('lightsTutorialDone').addEventListener('click',()=>startLightsOut('easy'));}
function startLightsOut(difficulty){prepareGeneric('正在生成可解关卡…');let puzzle;try{puzzle=generateLightsOut(difficulty);}catch(error){toast(error.message);return openLightsOut();}state={kind:'lights-out',...puzzle,initial:[...puzzle.board],board:[...puzzle.board],optimal:puzzle.solution.length,moves:0,hints:0,history:[],startedAt:Date.now(),timer:null};renderLightsOut();}
function renderLightsOut(message='关闭所有发光格'){stage.className='game-stage lights-stage';const lit=state.board.filter(Boolean).length;document.getElementById('lives').textContent=`亮灯 ${lit} · 移动 ${state.moves}`;document.getElementById('level').textContent=`${state.size}×${state.size} · 最少 ${state.optimal}`;stage.innerHTML=`<div class="stage-inner"><h2>开关灯</h2><p class="muted">${message}</p><div class="lights-board" style="--lights-size:${state.size}">${state.board.map((value,index)=>`<button class="light-cell ${value?'lit':''}" data-light="${index}" aria-label="第 ${Math.floor(index/state.size)+1} 行第 ${index%state.size+1} 列，${value?'亮':'灭'}" aria-pressed="${!!value}"><span></span></button>`).join('')}</div><div class="lights-legend"><span><i class="on"></i>亮灯</span><span><i></i>熄灭</span><span>点击影响十字相邻格</span></div><div class="lights-toolbar"><button class="btn btn-secondary" id="undoLights">撤销</button><button class="btn btn-secondary" id="restartLights">重开</button><button class="btn btn-secondary" id="hintLights">智能一步 · 25 XP</button><button class="btn btn-secondary" id="newLights">换题</button><button class="btn btn-secondary" id="closeLights">主页</button></div></div>`;stage.querySelector('.lights-board').addEventListener('click',event=>{const cell=event.target.closest('[data-light]');if(cell)pressLight(Number(cell.dataset.light));});document.getElementById('undoLights').addEventListener('click',undoLight);document.getElementById('restartLights').addEventListener('click',()=>{state.board=[...state.initial];state.moves=0;state.hints=0;state.history=[];state.startedAt=Date.now();renderLightsOut('本局已经重新开始');});document.getElementById('hintLights').addEventListener('click',hintLightsOut);document.getElementById('newLights').addEventListener('click',()=>startLightsOut(state.difficulty));document.getElementById('closeLights').addEventListener('click',closeGame);}
function pressLight(index,fromHint=false){state.history.push([...state.board]);state.board=toggleLights(state.board,state.size,index);state.moves++;if(state.board.every(value=>value===0)){renderLightsOut(fromHint?'智能提示完成了最后一步':'全部灯光已经熄灭');return state.timer=setTimeout(finishLightsOut,300);}renderLightsOut(fromHint?'AI 已执行当前最短解的下一步':'继续观察灯光变化');}
function undoLight(){const previous=state.history.pop();if(!previous)return toast('还没有可撤销的操作');state.board=previous;state.moves=Math.max(0,state.moves-1);renderLightsOut('已撤销上一步');}
function hintLightsOut(){if(progress.xp<25)return toast('积分不足');const solution=solveLightsOut(state.board,state.size);if(!solution?.length)return toast('当前棋盘已经完成');progress.xp-=25;state.hints++;saveProgress();pressLight(solution[0],true);}
function finishLightsOut(){if(state.kind!=='lights-out')return;const seconds=Math.max(1,Math.round((Date.now()-state.startedAt)/1000)),{difficulty,moves,hints,optimal,size}=state;completeGame('lights-out','开关灯',Math.max(100,700+size*50-(moves-optimal)*20-hints*45-seconds*2),[{value:`${size}×${size}`,label:'棋盘'},{value:`${moves}/${optimal}`,label:'步数/最少'},{value:`${seconds}s`,label:'用时'}],()=>startLightsOut(difficulty));}
