// 逻辑矩阵 — unique-solution deduction game.
registerGame('logic-grid', openLogicGrid);

const LOGIC_GRID_LEVELS = {
  easy: { name: '入门', n: 3, categories: 2, desc: '3 人 · 双属性' },
  medium: { name: '标准', n: 4, categories: 2, desc: '4 人 · 双属性' },
  hard: { name: '进阶', n: 4, categories: 3, desc: '4 人 · 三属性' },
  expert: { name: '困难', n: 5, categories: 3, desc: '5 人 · 三属性' }
};
const LOGIC_PEOPLE = ['阿宁','小北','程野','朵朵','林川'];
const LOGIC_CATEGORY_POOL = [
  { id:'color', name:'颜色', items:['红色','蓝色','绿色','黄色','紫色'] },
  { id:'drink', name:'饮品', items:['清茶','咖啡','牛奶','果汁','汽水'] },
  { id:'pet', name:'宠物', items:['猫咪','小狗','白兔','鹦鹉','金鱼'] },
  { id:'hobby', name:'爱好', items:['阅读','绘画','跑步','音乐','园艺'] }
];
let logicGridNonce = 0;

function logicPermutations(values){if(values.length<2)return [values];const out=[];values.forEach((value,index)=>logicPermutations([...values.slice(0,index),...values.slice(index+1)]).forEach(rest=>out.push([value,...rest])));return out;}
function logicClueMatches(assignments,clue){if(clue.type==='personEq')return assignments[clue.cat][clue.person]===clue.item;if(clue.type==='personNeq')return assignments[clue.cat][clue.person]!==clue.item;const personA=assignments[clue.catA].indexOf(clue.itemA),personB=assignments[clue.catB].indexOf(clue.itemB);return clue.type==='crossEq'?personA===personB:personA!==personB;}
function solveLogicGrid(n,categoryCount,clues,limit=2){const base=logicPermutations([...Array(n)].map((_,i)=>i)),direct=[...Array(categoryCount)].map((_,cat)=>base.filter(perm=>clues.every(clue=>!('cat' in clue)||clue.cat!==cat||logicClueMatches([...[...Array(categoryCount)].map(()=>perm)],clue)))),assigned=Array(categoryCount).fill(null);let count=0,solution=null;function search(depth){if(count>=limit)return;if(depth===categoryCount){if(clues.every(clue=>logicClueMatches(assigned,clue))){count++;if(!solution)solution=assigned.map(x=>[...x]);}return;}let cat=-1,options=null;for(let c=0;c<categoryCount;c++)if(!assigned[c]&&(options===null||direct[c].length<options.length)){cat=c;options=direct[c];}for(const perm of options){assigned[cat]=perm;const valid=clues.every(clue=>{if('cat' in clue)return clue.cat!==cat||logicClueMatches(assigned,clue);return !assigned[clue.catA]||!assigned[clue.catB]||logicClueMatches(assigned,clue);});if(valid)search(depth+1);assigned[cat]=null;if(count>=limit)return;}}search(0);return{count,solution};}
function logicClueText(clue,puzzle){const category=cat=>puzzle.categories[cat],item=(cat,index)=>category(cat).items[index];if(clue.type==='personEq')return`${puzzle.people[clue.person]} 的${category(clue.cat).name}是“${item(clue.cat,clue.item)}”`;if(clue.type==='personNeq')return`${puzzle.people[clue.person]} 的${category(clue.cat).name}不是“${item(clue.cat,clue.item)}”`;const relation=clue.type==='crossEq'?'属于同一个人':'不属于同一个人';return`“${item(clue.catA,clue.itemA)}”与“${item(clue.catB,clue.itemB)}”${relation}`;}
function buildLogicCluePool(solution,n,categoryCount){const pool=[];for(let cat=0;cat<categoryCount;cat++)for(let person=0;person<n;person++){pool.push({type:'personEq',cat,person,item:solution[cat][person]});for(let item=0;item<n;item++)if(item!==solution[cat][person])pool.push({type:'personNeq',cat,person,item});}for(let catA=0;catA<categoryCount;catA++)for(let catB=catA+1;catB<categoryCount;catB++){for(let person=0;person<n;person++)pool.push({type:'crossEq',catA,catB,itemA:solution[catA][person],itemB:solution[catB][person]});for(let itemA=0;itemA<n;itemA++)for(let itemB=0;itemB<n;itemB++)if(solution[catA].indexOf(itemA)!==solution[catB].indexOf(itemB))pool.push({type:'crossNeq',catA,catB,itemA,itemB});}return pool;}
function generateLogicGrid(difficulty){const config=LOGIC_GRID_LEVELS[difficulty],nonce=++logicGridNonce,baseSeed=Date.now()+nonce*15485863;for(let attempt=0;attempt<80;attempt++){const random=seededRandom((baseSeed+attempt*104729)>>>0),people=shuffle(LOGIC_PEOPLE,random).slice(0,config.n),categories=shuffle(LOGIC_CATEGORY_POOL,random).slice(0,config.categories).map(category=>({...category,items:shuffle(category.items,random).slice(0,config.n)})),solution=[...Array(config.categories)].map(()=>shuffle([...Array(config.n)].map((_,i)=>i),random)),allClues=buildLogicCluePool(solution,config.n,config.categories),clues=[...allClues];for(const clue of shuffle(allClues,random)){const index=clues.indexOf(clue),trial=[...clues.slice(0,index),...clues.slice(index+1)];if(solveLogicGrid(config.n,config.categories,trial,2).count===1)clues.splice(index,1);}const solved=solveLogicGrid(config.n,config.categories,clues,2),signature=`${difficulty}:${categories.map(c=>c.id).join('.')}:${solution.map(x=>x.join('')).join('.')}`;if(solved.count===1&&!progress.seen.logicGrid.includes(signature)){progress.seen.logicGrid=[signature,...progress.seen.logicGrid].slice(0,80);saveProgress();return{difficulty,...config,people,categories,solution,clues,signature};}}throw new Error('暂时无法生成唯一解逻辑矩阵，请重试');}

function openLogicGrid(){state={kind:'logic-grid-menu',timer:null};prepareGeneric('逻辑矩阵');stage.innerHTML=`<div class="stage-inner"><p class="eyebrow">条件推理 · 唯一答案</p><h2>选择逻辑矩阵难度</h2><p>根据线索确定人物与多个属性之间的一一对应关系。</p><div class="choice-grid">${Object.entries(LOGIC_GRID_LEVELS).map(([id,level])=>`<button class="choice" data-logic-level="${id}"><b>${level.name}</b><br><small>${level.desc}</small></button>`).join('')}</div><button class="btn btn-secondary" id="logicTutorial" style="margin-top:12px">玩法教程</button></div>`;stage.querySelector('.choice-grid').addEventListener('click',event=>{const button=event.target.closest('[data-logic-level]');if(button)startLogicGrid(button.dataset.logicLevel);});document.getElementById('logicTutorial').addEventListener('click',showLogicGridTutorial);}
function showLogicGridTutorial(){stage.innerHTML=`<div class="stage-inner"><p class="eyebrow">逻辑矩阵教程</p><h2>用 ✓ 确定，用 × 排除</h2><p>每个人在每类属性中只能对应一项，每个属性也只能属于一个人。阅读全部线索，先排除不可能，再确定唯一对应关系。</p><div class="clue-list"><p><b>× 排除</b>：线索明确说明某组合不成立。</p><p><b>✓ 确定</b>：选定后，同一行和同一列的其他组合会自动排除。</p><p><b>切换属性</b>：分别完成颜色、饮品、宠物等矩阵。</p></div><button class="btn btn-primary" id="logicTutorialDone">选择难度</button></div>`;document.getElementById('logicTutorialDone').addEventListener('click',openLogicGrid);}
function startLogicGrid(difficulty){prepareGeneric('正在生成唯一线索…');let puzzle;try{puzzle=generateLogicGrid(difficulty);}catch(error){toast(error.message);return openLogicGrid();}state={kind:'logic-grid',...puzzle,marks:[...Array(puzzle.categories.length)].map(()=>Array(puzzle.n*puzzle.n).fill(0)),activeCat:0,tool:2,history:[],moves:0,hints:0,startedAt:Date.now(),feedback:'先从最明确的线索开始',timer:null};renderLogicGrid();}
function renderLogicGrid(){stage.className='game-stage logic-grid-stage';const category=state.categories[state.activeCat],confirmed=state.marks.reduce((sum,marks)=>sum+marks.filter(v=>v===1).length,0);document.getElementById('lives').textContent=`${LOGIC_GRID_LEVELS[state.difficulty].name} · 已确定 ${confirmed}/${state.n*state.categories.length}`;document.getElementById('level').textContent=`${state.n} 人 · ${state.clues.length} 线索`;stage.innerHTML=`<div class="stage-inner"><h2>逻辑矩阵</h2><p class="muted">${state.feedback}</p><div class="logic-clues">${state.clues.map((clue,index)=>`<p><span>${index+1}.</span>${logicClueText(clue,state)}</p>`).join('')}</div><div class="logic-tabs">${state.categories.map((cat,index)=>`<button class="${index===state.activeCat?'active':''}" data-logic-tab="${index}">${cat.name}</button>`).join('')}</div><div class="logic-matrix" style="--logic-n:${state.n}"><div class="logic-axis">人物</div>${category.items.map(item=>`<div class="logic-col-head">${item}</div>`).join('')}${state.people.map((person,p)=>`<div class="logic-row-head">${person}</div>${category.items.map((_,item)=>{const value=state.marks[state.activeCat][p*state.n+item];return`<button class="logic-cell ${value===1?'yes':value===2?'no':''}" data-logic-cell="${p},${item}" aria-label="${person}与${category.items[item]}">${value===1?'✓':value===2?'×':''}</button>`;}).join('')}`).join('')}</div><div class="logic-toolbar"><button class="btn btn-secondary ${state.tool===1?'active':''}" data-logic-tool="1">✓ 确定</button><button class="btn btn-secondary ${state.tool===2?'active':''}" data-logic-tool="2">× 排除</button><button class="btn btn-secondary" id="undoLogic">撤销</button><button class="btn btn-primary" id="submitLogic" style="width:auto">提交</button><button class="btn btn-secondary" id="hintLogic">提示 · 35 XP</button><button class="btn btn-secondary" id="newLogic">换题</button><button class="btn btn-secondary" id="closeLogic">主页</button></div></div>`;bindLogicGrid();}
function applyLogicMark(person,item,value,record=true){const cat=state.activeCat,marks=state.marks[cat];if(record)state.history.push([cat,[...marks]]);if(value===1){for(let i=0;i<state.n;i++){marks[person*state.n+i]=i===item?1:2;marks[i*state.n+item]=i===person?1:2;}}else marks[person*state.n+item]=marks[person*state.n+item]===2?0:2;state.moves++;renderLogicGrid();}
function bindLogicGrid(){stage.querySelector('.logic-tabs').addEventListener('click',event=>{const button=event.target.closest('[data-logic-tab]');if(button){state.activeCat=Number(button.dataset.logicTab);renderLogicGrid();}});stage.querySelector('.logic-matrix').addEventListener('click',event=>{const cell=event.target.closest('[data-logic-cell]');if(!cell)return;const [person,item]=cell.dataset.logicCell.split(',').map(Number);applyLogicMark(person,item,state.tool);});stage.querySelectorAll('[data-logic-tool]').forEach(button=>button.addEventListener('click',()=>{state.tool=Number(button.dataset.logicTool);renderLogicGrid();}));document.getElementById('undoLogic').addEventListener('click',()=>{const last=state.history.pop();if(!last)return toast('还没有可撤销的操作');state.marks[last[0]]=last[1];state.activeCat=last[0];renderLogicGrid();});document.getElementById('submitLogic').addEventListener('click',submitLogicGrid);document.getElementById('hintLogic').addEventListener('click',hintLogicGrid);document.getElementById('newLogic').addEventListener('click',()=>startLogicGrid(state.difficulty));document.getElementById('closeLogic').addEventListener('click',closeGame);}
function submitLogicGrid(){for(let cat=0;cat<state.categories.length;cat++)for(let person=0;person<state.n;person++){const selected=state.marks[cat].findIndex((value,index)=>Math.floor(index/state.n)===person&&value===1);if(selected<0){state.feedback=`${state.people[person]} 的${state.categories[cat].name}还没有确定`;return renderLogicGrid();}if(selected%state.n!==state.solution[cat][person]){state.feedback='还有对应关系与线索不符，请继续排除';return renderLogicGrid();}}const seconds=Math.max(1,Math.round((Date.now()-state.startedAt)/1000)),{difficulty,moves,hints}=state;completeGame('logic-grid','逻辑矩阵',Math.max(100,720+state.n*55-state.clues.length*2-moves-hints*60-seconds*2),[{value:LOGIC_GRID_LEVELS[difficulty].name,label:'难度'},{value:state.clues.length,label:'线索'},{value:`${seconds}s`,label:'用时'}],()=>startLogicGrid(difficulty));}
function hintLogicGrid(){if(progress.xp<35)return toast('积分不足');let target=null;for(let cat=0;cat<state.categories.length&&!target;cat++)for(let person=0;person<state.n&&!target;person++){const item=state.solution[cat][person];if(state.marks[cat][person*state.n+item]!==1)target={cat,person,item};}if(!target)return toast('所有对应关系已经确定');progress.xp-=35;state.hints++;saveProgress();state.activeCat=target.cat;state.feedback=`已确定：${state.people[target.person]} 的${state.categories[target.cat].name}`;applyLogicMark(target.person,target.item,1);}
