// 一笔画 — loaded as a classic script to support file:// usage.
registerGame('stroke', openOneStroke);
const STROKE_LEVELS=[
  {name:'三角回环',nodes:[[50,14],[16,78],[84,78]],edges:[[0,1],[1,2],[2,0]]},
  {name:'方中斜线',nodes:[[18,18],[82,18],[82,82],[18,82]],edges:[[0,1],[1,2],[2,3],[3,0],[0,2]]},
  {name:'一座小屋',nodes:[[50,10],[18,42],[82,42],[18,86],[82,86]],edges:[[0,1],[0,2],[1,2],[1,3],[2,4],[3,4]]},
  {name:'交叠双翼',nodes:[[15,20],[50,50],[85,20],[15,80],[85,80]],edges:[[0,1],[1,2],[2,4],[4,1],[1,3],[3,0]]},
  {name:'五点星路',nodes:[[50,8],[88,78],[12,32],[88,32],[12,78]],edges:[[0,1],[1,2],[2,3],[3,4],[4,0]]}
];
function openOneStroke(){state={kind:'stroke',level:0,totalMoves:0,timer:null,startedAt:Date.now()};startStrokeLevel();}
function startStrokeLevel(){state.current=null;state.used=new Set();prepareGeneric('一笔画');renderOneStroke();}
function renderOneStroke(message='点击任意起点开始'){const level=STROKE_LEVELS[state.level];document.getElementById('lives').textContent=`线段 ${state.used.size} / ${level.edges.length}`;document.getElementById('level').textContent=`${state.level+1} / ${STROKE_LEVELS.length}`;stage.innerHTML=`<div class="stage-inner"><h2>${level.name}</h2><p class="muted">${message}</p><svg class="stroke-board" viewBox="0 0 100 100" aria-label="一笔画图形">${level.edges.map((e,i)=>`<line class="stroke-edge ${state.used.has(i)?'used':''}" x1="${level.nodes[e[0]][0]}" y1="${level.nodes[e[0]][1]}" x2="${level.nodes[e[1]][0]}" y2="${level.nodes[e[1]][1]}"/>`).join('')}${level.nodes.map((n,i)=>`<circle class="stroke-node ${state.current===i?'current':''}" data-stroke-node="${i}" cx="${n[0]}" cy="${n[1]}" r="5"/>`).join('')}</svg><div class="game-actions"><button class="btn btn-secondary" id="resetStroke">重画本关</button></div></div>`;stage.querySelector('.stroke-board').addEventListener('click',e=>{const n=e.target.dataset.strokeNode;if(n!==undefined)tapStroke(Number(n));});document.getElementById('resetStroke').addEventListener('click',startStrokeLevel);}
function tapStroke(node){if(state.current===null){state.current=node;return renderOneStroke('沿着未使用的线继续');}const level=STROKE_LEVELS[state.level],edgeIndex=level.edges.findIndex((e,i)=>!state.used.has(i)&&((e[0]===state.current&&e[1]===node)||(e[1]===state.current&&e[0]===node)));if(edgeIndex<0)return renderOneStroke('这两个点之间没有可用线段');state.used.add(edgeIndex);state.current=node;state.totalMoves++;if(state.used.size===level.edges.length){state.level++;if(state.level===STROKE_LEVELS.length){const seconds=Math.round((Date.now()-state.startedAt)/1000);return completeGame('stroke','一笔画',Math.max(100,999-seconds*2),[{value:'5/5',label:'完成关卡'},{value:state.totalMoves,label:'经过线段'},{value:`${seconds}s`,label:'用时'}],openOneStroke);}return state.timer=setTimeout(startStrokeLevel,500);}renderOneStroke();}
