// 赛马逻辑 — loaded as a classic script to support file:// usage.
registerGame('race', openRaceLogic);
const HORSE_NAMES=['赤焰','青锋','白羽','黑曜','金铃','紫电','雪影'];
function permutations(values){if(values.length<2)return [values];const out=[];values.forEach((v,i)=>permutations([...values.slice(0,i),...values.slice(i+1)]).forEach(rest=>out.push([v,...rest])));return out;}
function raceClueMatches(order,clue){const a=order.indexOf(clue.a),b=clue.b===undefined?-1:order.indexOf(clue.b);return clue.type==='ahead'?a<b:clue.type==='next'?b===a+1:clue.type==='place'?a===clue.place:false;}
function raceClueText(clue,names){return clue.type==='ahead'?`${names[clue.a]} 排在 ${names[clue.b]} 前面`:clue.type==='next'?`${names[clue.b]} 紧跟在 ${names[clue.a]} 后面`:`${names[clue.a]} 获得第 ${clue.place+1} 名`;}
function generateRacePuzzle(difficulty){const n={easy:4,medium:5,hard:6,expert:7}[difficulty],names=HORSE_NAMES.slice(0,n);for(let attempt=0;attempt<80;attempt++){const solution=shuffle([...Array(n)].map((_,i)=>i)),pool=[];for(let i=0;i<n;i++)for(let j=i+1;j<n;j++)pool.push({type:'ahead',a:solution[i],b:solution[j],id:`a${solution[i]}${solution[j]}`});for(let i=0;i<n-1;i++)pool.push({type:'next',a:solution[i],b:solution[i+1],id:`n${solution[i]}${solution[i+1]}`});const exactCount=difficulty==='easy'?2:difficulty==='medium'?1:0;shuffle([...Array(n)].map((_,i)=>i)).slice(0,exactCount).forEach(i=>pool.push({type:'place',a:solution[i],place:i,id:`p${solution[i]}${i}`}));let candidates=permutations([...Array(n)].map((_,i)=>i)),clues=[];for(const clue of shuffle(pool)){const next=candidates.filter(order=>raceClueMatches(order,clue));if(next.length<candidates.length){clues.push(clue);candidates=next;}if(candidates.length===1)break;}const signature=`${difficulty}:${solution.join('')}:${clues.map(c=>c.id).sort().join('.')}`;if(candidates.length===1&&!progress.seen.race.includes(signature)){progress.seen.race=[signature,...progress.seen.race].slice(0,80);saveProgress();return{difficulty,names,solution,clues,signature};}}return generateRacePuzzle(difficulty);}
function openRaceLogic(){state={kind:'race-menu',timer:null};prepareGeneric('赛马逻辑');stage.innerHTML=`<div class="stage-inner"><p class="eyebrow">唯一答案逻辑题</p><h2>选择赛马难度</h2><p>根据所有线索推断最终名次。每道题生成后都会验证唯一解。</p><div class="choice-grid">${[['easy','初级 · 4 匹'],['medium','中级 · 5 匹'],['hard','困难 · 6 匹'],['expert','专家 · 7 匹']].map(([id,label])=>`<button class="choice" data-race-level="${id}">${label}</button>`).join('')}</div></div>`;stage.querySelector('.choice-grid').addEventListener('click',e=>{const b=e.target.closest('[data-race-level]');if(b)startRaceLogic(b.dataset.raceLevel);});}
function startRaceLogic(difficulty){const puzzle=generateRacePuzzle(difficulty),order=shuffle([...puzzle.solution]);if(order.join('')===puzzle.solution.join(''))[order[0],order[1]]=[order[1],order[0]];state={kind:'race',...puzzle,order,selected:null,moves:0,hints:0,startedAt:Date.now(),timer:null};renderRaceLogic();}
function renderRaceLogic(message='点击两匹马可交换名次'){document.getElementById('lives').textContent=`调整 ${state.moves}`;document.getElementById('level').textContent=`${state.names.length} 匹 · ${state.clues.length} 条线索`;stage.innerHTML=`<div class="stage-inner"><h2>赛马逻辑</h2><div class="clue-list">${state.clues.map((c,i)=>`<p><span class="meta">${i+1}.</span> ${raceClueText(c,state.names)}</p>`).join('')}</div><div class="race-list">${state.order.map((horse,rank)=>`<div class="race-horse ${state.selected===rank?'selected':''}" data-race-rank="${rank}" role="button" tabindex="0"><span class="race-rank">${rank+1}</span><b>${state.names[horse]}</b><span class="race-controls"><button data-race-move="${rank},-1" aria-label="上移">↑</button><button data-race-move="${rank},1" aria-label="下移">↓</button></span></div>`).join('')}</div><p class="feedback">${message}</p><div class="game-actions"><button class="btn btn-primary" id="submitRace" style="width:auto">提交名次</button><button class="btn btn-secondary" id="hintRace">提示 · 30 XP</button><button class="btn btn-secondary" id="newRace">换一题</button></div></div>`;stage.querySelector('.race-list').addEventListener('click',e=>{const move=e.target.closest('[data-race-move]');if(move){const [rank,dir]=move.dataset.raceMove.split(',').map(Number);return moveRaceHorse(rank,dir);}const row=e.target.closest('[data-race-rank]');if(row)selectRaceHorse(Number(row.dataset.raceRank));});document.getElementById('submitRace').addEventListener('click',submitRaceLogic);document.getElementById('hintRace').addEventListener('click',hintRaceLogic);document.getElementById('newRace').addEventListener('click',()=>startRaceLogic(state.difficulty));}
function selectRaceHorse(rank){if(state.selected===null){state.selected=rank;return renderRaceLogic('再点击一匹马进行交换');}if(state.selected!==rank){[state.order[state.selected],state.order[rank]]=[state.order[rank],state.order[state.selected]];state.moves++;}state.selected=null;renderRaceLogic();}
function moveRaceHorse(rank,dir){const target=rank+dir;if(target<0||target>=state.order.length)return;[state.order[rank],state.order[target]]=[state.order[target],state.order[rank]];state.moves++;state.selected=null;renderRaceLogic();}
function submitRaceLogic(){if(state.order.join('')!==state.solution.join(''))return renderRaceLogic('名次还不符合全部线索');const seconds=Math.round((Date.now()-state.startedAt)/1000);completeGame('race','赛马逻辑',Math.max(100,999-state.moves*12-state.hints*45-seconds*2),[{value:state.names.length,label:'参赛马匹'},{value:state.clues.length,label:'线索'},{value:`${seconds}s`,label:'用时'}],()=>startRaceLogic(state.difficulty));}
function hintRaceLogic(){if(progress.xp<30)return toast('积分不足');const index=state.order.findIndex((horse,i)=>horse!==state.solution[i]);if(index<0)return;const correctHorse=state.solution[index],from=state.order.indexOf(correctHorse);state.order.splice(from,1);state.order.splice(index,0,correctHorse);progress.xp-=30;state.hints++;saveProgress();renderRaceLogic(`已确定第 ${index+1} 名`);}
