// 摩天楼 — Latin-square visibility puzzles.
registerGame('skyscrapers', openSkyscrapers);
const SKY_LEVELS={easy:{name:'入门',n:4,clues:1,givens:.34},medium:{name:'标准',n:5,clues:.86,givens:.24},hard:{name:'进阶',n:6,clues:.72,givens:.18},expert:{name:'困难',n:7,clues:.6,givens:.14},master:{name:'大师',n:8,clues:.5,givens:.12}};let skyNonce=0;
function skyscraperVisible(line){let max=0,count=0;for(const h of line)if(h>max){max=h;count++;}return count;}
function generateSkyscrapers(difficulty,providedRandom=null,testMode=false){const cfg=SKY_LEVELS[difficulty],random=providedRandom||seededRandom((Date.now()+ ++skyNonce*86028121)>>>0),base=shuffle([...Array(cfg.n)].map((_,i)=>i),random),rowShift=shuffle([...Array(cfg.n)].map((_,i)=>i),random),solution=[];for(let r=0;r<cfg.n;r++)for(let c=0;c<cfg.n;c++)solution.push(base[(rowShift[r]+c)%cfg.n]+1);const lines={top:[],right:[],bottom:[],left:[]};for(let i=0;i<cfg.n;i++){const row=solution.slice(i*cfg.n,(i+1)*cfg.n),col=[...Array(cfg.n)].map((_,r)=>solution[r*cfg.n+i]);lines.left[i]=skyscraperVisible(row);lines.right[i]=skyscraperVisible([...row].reverse());lines.top[i]=skyscraperVisible(col);lines.bottom[i]=skyscraperVisible([...col].reverse());}Object.values(lines).forEach(side=>side.forEach((_,i)=>{if(random()>cfg.clues)side[i]=0;}));const givens=Array(cfg.n*cfg.n).fill(0);shuffle([...Array(givens.length)].map((_,i)=>i),random).slice(0,Math.round(givens.length*cfg.givens)).forEach(i=>givens[i]=solution[i]);const signature=`${cfg.n}:${solution.join('')}:${Object.values(lines).flat().join('')}:${givens.join('')}`;if(!testMode){if(progress.seen.skyscrapers.includes(signature))return generateSkyscrapers(difficulty,null,false);progress.seen.skyscrapers=[signature,...progress.seen.skyscrapers].slice(0,80);saveProgress();}return{difficulty,...cfg,solution,lines,givens,signature};}
function skyscraperSolutionValid(p){const n=p.n;for(let i=0;i<n;i++){const row=p.solution.slice(i*n,(i+1)*n),col=[...Array(n)].map((_,r)=>p.solution[r*n+i]);if(new Set(row).size!==n||new Set(col).size!==n)return false;}return true;}
function openSkyscrapers(){state={kind:'sky-menu'};prepareGeneric('摩天楼');stage.innerHTML=`<div class="stage-inner"><p class="eyebrow">视线推理 · 拉丁方阵</p><h2>选择摩天楼难度</h2><p>每行每列填入 1 到 N；外围数字表示从该方向能看到几栋楼。</p><div class="choice-grid">${Object.entries(SKY_LEVELS).map(([id,l])=>`<button class="choice" data-sky="${id}"><b>${l.name} · ${l.n}×${l.n}</b><br><small>${Math.round(l.clues*100)}% 视线提示</small></button>`).join('')}</div></div>`;stage.querySelector('.choice-grid').onclick=e=>{const b=e.target.closest('[data-sky]');if(b)startSkyscrapers(b.dataset.sky);};}
function startSkyscrapers(difficulty){const p=generateSkyscrapers(difficulty);state={kind:'skyscrapers',...p,values:[...p.givens],selected:p.givens.findIndex(v=>!v),history:[],hints:0,mistakes:0,startedAt:Date.now(),feedback:'选择空格并填入楼层高度'};renderSkyscrapers();}
function renderSkyscrapers(){stage.className='game-stage sky-stage';const n=state.n;document.getElementById('lives').textContent=`${SKY_LEVELS[state.difficulty].name} · 已填 ${state.values.filter(Boolean).length}/${n*n}`;document.getElementById('level').textContent=`${n}×${n}`;const clue=v=>`<span>${v||''}</span>`;stage.innerHTML=`<div class="stage-inner"><h2>摩天楼</h2><p class="muted">${state.feedback}</p><div class="sky-wrap" style="--sky-n:${n}"><div></div><div class="sky-clues horizontal">${state.lines.top.map(clue).join('')}</div><div></div><div class="sky-clues vertical">${state.lines.left.map(clue).join('')}</div><div class="sky-board">${state.values.map((v,i)=>`<button class="sky-cell ${state.givens[i]?'given':''} ${i===state.selected?'selected':''}" data-sky-cell="${i}">${v||''}</button>`).join('')}</div><div class="sky-clues vertical">${state.lines.right.map(clue).join('')}</div><div></div><div class="sky-clues horizontal">${state.lines.bottom.map(clue).join('')}</div></div><div class="sky-pad">${[...Array(n)].map((_,i)=>`<button data-sky-number="${i+1}">${i+1}</button>`).join('')}<button data-sky-number="0">⌫</button></div><div class="puzzle-toolbar"><button class="btn btn-secondary" id="undoSky">撤销</button><button class="btn btn-secondary" id="checkSky">查错</button><button class="btn btn-secondary" id="hintSky">AI 一步 · 30 XP</button><button class="btn btn-secondary" id="newSky">换题</button><button class="btn btn-secondary" id="closeSky">主页</button></div></div>`;stage.querySelector('.sky-board').onclick=e=>{const b=e.target.closest('[data-sky-cell]');if(b&&!state.givens[+b.dataset.skyCell]){state.selected=+b.dataset.skyCell;renderSkyscrapers();}};stage.querySelector('.sky-pad').onclick=e=>{const b=e.target.closest('[data-sky-number]');if(b)enterSky(+b.dataset.skyNumber);};document.getElementById('undoSky').onclick=()=>{const p=state.history.pop();if(!p)return toast('还没有可撤销的操作');state.values=p;renderSkyscrapers();};document.getElementById('checkSky').onclick=checkSky;document.getElementById('hintSky').onclick=hintSky;document.getElementById('newSky').onclick=()=>startSkyscrapers(state.difficulty);document.getElementById('closeSky').onclick=closeGame;}
function enterSky(value){if(state.selected<0||state.givens[state.selected])return;state.history.push([...state.values]);state.values[state.selected]=value;if(state.values.every((v,i)=>v===state.solution[i]))return renderSkyscrapers(),setTimeout(finishSky,250);state.feedback=value?'已填写楼层':'已清除当前格';renderSkyscrapers();}
function checkSky(){const wrong=state.values.filter((v,i)=>v&&v!==state.solution[i]).length;state.mistakes+=!!wrong;state.feedback=wrong?`发现 ${wrong} 个错误数字`:'目前填写均正确';renderSkyscrapers();}
function hintSky(){if(progress.xp<30)return toast('积分不足');const i=state.values.findIndex((v,j)=>v!==state.solution[j]);if(i<0)return;state.history.push([...state.values]);state.values[i]=state.solution[i];state.selected=i;state.hints++;progress.xp-=30;saveProgress();state.feedback='AI 已填入一个确定高度';if(state.values.every((v,j)=>v===state.solution[j]))return renderSkyscrapers(),setTimeout(finishSky,250);renderSkyscrapers();}
function finishSky(){if(state.kind!=='skyscrapers')return;const sec=Math.max(1,Math.round((Date.now()-state.startedAt)/1000)),d=state.difficulty;completeGame('skyscrapers','摩天楼',720+state.n*40-state.hints*45-state.mistakes*30-sec,[{value:`${state.n}×${state.n}`,label:'棋盘'},{value:state.hints,label:'辅助'},{value:`${sec}s`,label:'用时'}],()=>startSkyscrapers(d));}
