// 推箱子 — procedurally sampled boards verified by breadth-first search.
registerGame('sokoban', openSokoban);
const SOKOBAN_LEVELS={easy:{name:'入门',n:6,boxes:1,walls:1},medium:{name:'标准',n:6,boxes:2,walls:1},hard:{name:'进阶',n:7,boxes:2,walls:3},expert:{name:'困难',n:7,boxes:3,walls:3},master:{name:'大师',n:8,boxes:3,walls:6}};let sokobanNonce=0;
const SOKO_DIRS=[[-1,0,'up'],[1,0,'down'],[0,-1,'left'],[0,1,'right']];
function sokobanMove(puzzle,player,boxes,direction){const [dr,dc]=SOKO_DIRS.find(d=>d[2]===direction),r=Math.floor(player/puzzle.n),c=player%puzzle.n,nr=r+dr,nc=c+dc,next=nr*puzzle.n+nc;if(nr<0||nr>=puzzle.n||nc<0||nc>=puzzle.n||puzzle.walls.has(next))return null;const set=new Set(boxes);if(set.has(next)){const br=nr+dr,bc=nc+dc,beyond=br*puzzle.n+bc;if(br<0||br>=puzzle.n||bc<0||bc>=puzzle.n||puzzle.walls.has(beyond)||set.has(beyond))return null;set.delete(next);set.add(beyond);}return{player:next,boxes:[...set].sort((a,b)=>a-b)};}
function solveSokoban(puzzle,player=puzzle.player,boxes=puzzle.boxes,limit=90000){const startBoxes=[...boxes].sort((a,b)=>a-b),key=(p,b)=>`${p}:${b.join('.')}`,queue=[{player,boxes:startBoxes,path:[]}],seen=new Set([key(player,startBoxes)]);for(let head=0;head<queue.length&&head<limit;head++){const cur=queue[head];if(cur.boxes.every(b=>puzzle.goals.has(b)))return cur.path;for(const dir of SOKO_DIRS){const next=sokobanMove(puzzle,cur.player,cur.boxes,dir[2]);if(!next)continue;const k=key(next.player,next.boxes);if(seen.has(k))continue;seen.add(k);queue.push({...next,path:[...cur.path,dir[2]]});}}return null;}
function generateSokoban(difficulty,providedRandom=null,testMode=false){const cfg=SOKOBAN_LEVELS[difficulty],random=providedRandom||seededRandom((Date.now()+ ++sokobanNonce*122949829)>>>0);for(let attempt=0;attempt<300;attempt++){const walls=new Set();for(let r=0;r<cfg.n;r++)for(let c=0;c<cfg.n;c++)if(!r||!c||r===cfg.n-1||c===cfg.n-1)walls.add(r*cfg.n+c);const interior=[];for(let r=1;r<cfg.n-1;r++)for(let c=1;c<cfg.n-1;c++)interior.push(r*cfg.n+c);shuffle(interior,random).slice(0,cfg.walls).forEach(i=>walls.add(i));const free=shuffle(interior.filter(i=>!walls.has(i)),random),goals=new Set(free.slice(0,cfg.boxes)),boxes=free.slice(cfg.boxes,cfg.boxes*2).sort((a,b)=>a-b),player=free[cfg.boxes*2],puzzle={difficulty,...cfg,walls,goals,boxes,player},solution=solveSokoban(puzzle);if(!solution||solution.length<cfg.boxes*2||solution.length>100)continue;const signature=`${cfg.n}:${[...walls].join('.')}:${[...goals].join('.')}:${boxes.join('.')}:${player}`;if(!testMode){if(progress.seen.sokoban.includes(signature))continue;progress.seen.sokoban=[signature,...progress.seen.sokoban].slice(0,80);saveProgress();}return{...puzzle,solution,signature};}throw new Error('暂时无法生成可解推箱子关卡');}
function openSokoban(){state={kind:'sokoban-menu'};prepareGeneric('推箱子');stage.innerHTML=`<div class="stage-inner"><p class="eyebrow">空间规划 · 路径搜索</p><h2>选择推箱子难度</h2><p>只能推动、不能拉动箱子，把所有箱子送到圆点目标位。</p><div class="choice-grid">${Object.entries(SOKOBAN_LEVELS).map(([id,l])=>`<button class="choice" data-soko="${id}"><b>${l.name} · ${l.n}×${l.n}</b><br><small>${l.boxes} 个箱子</small></button>`).join('')}</div></div>`;stage.querySelector('.choice-grid').onclick=e=>{const b=e.target.closest('[data-soko]');if(b)startSokoban(b.dataset.soko);};}
function startSokoban(difficulty){prepareGeneric('正在搜索可解关卡…');let p;try{p=generateSokoban(difficulty);}catch(e){toast(e.message);return openSokoban();}state={kind:'sokoban',...p,initialPlayer:p.player,initialBoxes:[...p.boxes],history:[],moves:0,hints:0,startedAt:Date.now(),feedback:'滑动棋盘或使用方向键移动'};renderSokoban();}
function renderSokoban(){stage.className='game-stage sokoban-stage';document.getElementById('lives').textContent=`${SOKOBAN_LEVELS[state.difficulty].name} · 移动 ${state.moves}`;document.getElementById('level').textContent=`箱子 ${state.boxes.filter(b=>state.goals.has(b)).length}/${state.boxes.length}`;const boxes=new Set(state.boxes);stage.innerHTML=`<div class="stage-inner"><h2>推箱子</h2><p class="muted">${state.feedback}</p><div class="sokoban-board" style="--soko-n:${state.n}">${[...Array(state.n*state.n)].map((_,i)=>`<div class="soko-cell ${state.walls.has(i)?'wall':''} ${state.goals.has(i)?'goal':''} ${boxes.has(i)?'box':''} ${state.player===i?'player':''}">${state.player===i?'人':boxes.has(i)?'箱':''}</div>`).join('')}</div><div class="soko-dpad"><span></span><button data-soko-dir="up">↑</button><span></span><button data-soko-dir="left">←</button><button data-soko-dir="down">↓</button><button data-soko-dir="right">→</button></div><div class="puzzle-toolbar"><button class="btn btn-secondary" id="undoSoko">撤销</button><button class="btn btn-secondary" id="restartSoko">重开</button><button class="btn btn-secondary" id="hintSoko">AI 一步 · 25 XP</button><button class="btn btn-secondary" id="newSoko">换题</button><button class="btn btn-secondary" id="closeSoko">主页</button></div></div>`;stage.querySelectorAll('[data-soko-dir]').forEach(b=>b.onclick=()=>playSokoban(b.dataset.sokoDir));let start=null;const board=stage.querySelector('.sokoban-board');board.onpointerdown=e=>start={x:e.clientX,y:e.clientY};board.onpointerup=e=>{if(!start)return;const dx=e.clientX-start.x,dy=e.clientY-start.y;if(Math.max(Math.abs(dx),Math.abs(dy))>20)playSokoban(Math.abs(dx)>Math.abs(dy)?dx>0?'right':'left':dy>0?'down':'up');start=null;};document.getElementById('undoSoko').onclick=undoSokoban;document.getElementById('restartSoko').onclick=()=>{state.player=state.initialPlayer;state.boxes=[...state.initialBoxes];state.history=[];state.moves=0;renderSokoban();};document.getElementById('hintSoko').onclick=hintSokoban;document.getElementById('newSoko').onclick=()=>startSokoban(state.difficulty);document.getElementById('closeSoko').onclick=closeGame;}
function playSokoban(direction,fromHint=false){const next=sokobanMove(state,state.player,state.boxes,direction);if(!next)return toast('这个方向走不通');state.history.push({player:state.player,boxes:[...state.boxes]});state.player=next.player;state.boxes=next.boxes;state.moves++;state.feedback=fromHint?'AI 已执行当前解路的下一步':'继续规划箱子的落点';if(state.boxes.every(b=>state.goals.has(b)))return renderSokoban(),setTimeout(finishSokoban,250);renderSokoban();}
function undoSokoban(){const p=state.history.pop();if(!p)return toast('还没有可撤销的操作');state.player=p.player;state.boxes=p.boxes;state.moves=Math.max(0,state.moves-1);renderSokoban();}
function hintSokoban(){if(progress.xp<25)return toast('积分不足');const path=solveSokoban(state,state.player,state.boxes);if(!path?.length)return toast('当前状态无法找到解路，可撤销或重开');progress.xp-=25;state.hints++;saveProgress();playSokoban(path[0],true);}
function finishSokoban(){if(state.kind!=='sokoban')return;const sec=Math.max(1,Math.round((Date.now()-state.startedAt)/1000)),d=state.difficulty;completeGame('sokoban','推箱子',740+state.boxes.length*60-state.hints*40-state.moves-sec,[{value:state.boxes.length,label:'箱子'},{value:state.moves,label:'移动'},{value:`${sec}s`,label:'用时'}],()=>startSokoban(d));}
