// 星星战役 — row, column and connected-region star placement.
registerGame('star-battle', openStarBattle);
const STAR_LEVELS={easy:{name:'入门',n:6},medium:{name:'标准',n:7},hard:{name:'进阶',n:8},expert:{name:'困难',n:9},master:{name:'大师',n:10}};let starNonce=0;
function starSolution(n,random){let cols=[...Array(n)].map((_,i)=>(i*2)%n);if(new Set(cols).size<n)cols=[...Array(n)].map((_,i)=>i%2?Math.floor(n/2)+Math.floor(i/2):Math.floor(i/2));if(random()<.5)cols.reverse();const shift=Math.floor(random()*n);return cols.map(c=>(c+shift)%n);}
function makeStarRegions(n,stars,random){const regions=Array(n*n).fill(-1),front=[];stars.forEach((c,r)=>{const i=r*n+c;regions[i]=r;front.push(i);});let left=n*n-n,guard=0;while(left&&guard++<n*n*20){const index=front[Math.floor(random()*front.length)],r=Math.floor(index/n),c=index%n,neighbors=[[r-1,c],[r+1,c],[r,c-1],[r,c+1]].filter(([rr,cc])=>rr>=0&&rr<n&&cc>=0&&cc<n&&regions[rr*n+cc]<0);if(!neighbors.length)continue;const [rr,cc]=neighbors[Math.floor(random()*neighbors.length)],next=rr*n+cc;regions[next]=regions[index];front.push(next);left--;}return regions;}
function solveStarBattle(puzzle,limit=2){const solutions=[],usedCols=new Set(),usedRegions=new Set(),placed=[];function search(row){if(solutions.length>=limit)return;if(row===puzzle.n){solutions.push([...placed]);return;}for(let col=0;col<puzzle.n;col++){const index=row*puzzle.n+col,region=puzzle.regions[index];if(puzzle.lockedX.has(index)||usedCols.has(col)||usedRegions.has(region))continue;if(row&&Math.abs(col-placed[row-1])<=1)continue;placed[row]=col;usedCols.add(col);usedRegions.add(region);search(row+1);usedCols.delete(col);usedRegions.delete(region);}}search(0);return{count:solutions.length,solution:solutions[0],alternate:solutions[1]};}
function generateStarBattle(difficulty,providedRandom=null,testMode=false){const cfg=STAR_LEVELS[difficulty],random=providedRandom||seededRandom((Date.now()+ ++starNonce*104395303)>>>0),stars=starSolution(cfg.n,random),regions=makeStarRegions(cfg.n,stars,random),lockedX=new Set(),puzzle={difficulty,...cfg,stars,regions,lockedX};let solved=solveStarBattle(puzzle,2),guard=0;while(solved.count!==1&&guard++<cfg.n*cfg.n){const alternative=[solved.solution,solved.alternate].find(candidate=>candidate&&candidate.some((c,r)=>c!==stars[r])),cell=alternative?alternative.map((c,r)=>r*cfg.n+c).find(i=>!lockedX.has(i)&&stars[Math.floor(i/cfg.n)]!==i%cfg.n):null;if(cell==null)break;lockedX.add(cell);solved=solveStarBattle(puzzle,2);}const signature=`${cfg.n}:${regions.join('')}:${stars.join('.')}:${[...lockedX].join('.')}`;if(!testMode){if(progress.seen.starBattle.includes(signature))return generateStarBattle(difficulty,null,false);progress.seen.starBattle=[signature,...progress.seen.starBattle].slice(0,80);saveProgress();}return{...puzzle,signature};}
function starBattleValid(p,marks){const stars=marks.map((v,i)=>v===1?i:-1).filter(i=>i>=0);if(stars.length!==p.n)return false;for(const index of stars){const r=Math.floor(index/p.n),c=index%p.n;if(stars.some(other=>other!==index&&Math.abs(Math.floor(other/p.n)-r)<=1&&Math.abs(other%p.n-c)<=1))return false;}return[...Array(p.n)].every((_,i)=>stars.filter(x=>Math.floor(x/p.n)===i).length===1&&stars.filter(x=>x%p.n===i).length===1&&stars.filter(x=>p.regions[x]===i).length===1);}
function openStarBattle(){state={kind:'star-menu'};prepareGeneric('星星战役');stage.innerHTML=`<div class="stage-inner"><p class="eyebrow">区域推理 · 互不接触</p><h2>选择星星战役难度</h2><p>每行、每列和每个彩色区域各放 1 颗星，星星之间不能相邻，包括斜角。</p><div class="choice-grid">${Object.entries(STAR_LEVELS).map(([id,l])=>`<button class="choice" data-star="${id}"><b>${l.name}</b><br><small>${l.n}×${l.n}</small></button>`).join('')}</div></div>`;stage.querySelector('.choice-grid').onclick=e=>{const b=e.target.closest('[data-star]');if(b)startStarBattle(b.dataset.star);};}
function startStarBattle(difficulty){const p=generateStarBattle(difficulty),marks=Array(p.n*p.n).fill(0);p.lockedX.forEach(i=>marks[i]=2);state={kind:'star-battle',...p,marks,tool:1,history:[],hints:0,mistakes:0,startedAt:Date.now(),feedback:'每行、每列、每区各放一颗星'};renderStarBattle();}
function renderStarBattle(){stage.className='game-stage star-stage';const count=state.marks.filter(v=>v===1).length;document.getElementById('lives').textContent=`${STAR_LEVELS[state.difficulty].name} · 星星 ${count}/${state.n}`;document.getElementById('level').textContent=`${state.n}×${state.n}`;stage.innerHTML=`<div class="stage-inner"><h2>星星战役</h2><p class="muted">${state.feedback}</p><div class="star-board" style="--star-n:${state.n}">${state.marks.map((v,i)=>`<button class="star-cell region-${state.regions[i]%8} ${v===1?'starred':v===2?'crossed':''} ${state.lockedX.has(i)?'locked':''}" data-star-cell="${i}">${v===1?'★':v===2?'×':''}</button>`).join('')}</div><div class="puzzle-toolbar"><button class="btn btn-secondary ${state.tool===1?'active':''}" data-star-tool="1">★ 星星</button><button class="btn btn-secondary ${state.tool===2?'active':''}" data-star-tool="2">× 排除</button><button class="btn btn-secondary" id="undoStar">撤销</button><button class="btn btn-secondary" id="checkStar">查错</button><button class="btn btn-secondary" id="hintStar">AI 一步 · 25 XP</button><button class="btn btn-secondary" id="newStar">换题</button><button class="btn btn-secondary" id="closeStar">主页</button></div></div>`;stage.querySelector('.star-board').onclick=e=>{const b=e.target.closest('[data-star-cell]');if(b)markStar(+b.dataset.starCell);};stage.querySelectorAll('[data-star-tool]').forEach(b=>b.onclick=()=>{state.tool=+b.dataset.starTool;renderStarBattle();});document.getElementById('undoStar').onclick=()=>{const p=state.history.pop();if(!p)return toast('还没有可撤销的操作');state.marks=p;renderStarBattle();};document.getElementById('checkStar').onclick=()=>{const wrong=state.marks.filter((v,i)=>v===1&&state.stars[Math.floor(i/state.n)]!==i%state.n).length;state.mistakes+=!!wrong;state.feedback=wrong?`有 ${wrong} 颗星位置不正确`:'目前标记正确';renderStarBattle();};document.getElementById('hintStar').onclick=hintStarBattle;document.getElementById('newStar').onclick=()=>startStarBattle(state.difficulty);document.getElementById('closeStar').onclick=closeGame;}
function markStar(index){if(state.lockedX.has(index))return;state.history.push([...state.marks]);state.marks[index]=state.marks[index]===state.tool?0:state.tool;if(starBattleValid(state,state.marks))return renderStarBattle(),setTimeout(finishStarBattle,250);renderStarBattle();}
function hintStarBattle(){if(progress.xp<25)return toast('积分不足');let index=-1,target=0;for(let r=0;r<state.n;r++){const star=r*state.n+state.stars[r];if(state.marks[star]!==1){index=star;target=1;break;}}if(index<0)return toast('已经完成');state.history.push([...state.marks]);state.marks[index]=target;state.hints++;progress.xp-=25;saveProgress();state.feedback='AI 已放置一颗确定星星';if(starBattleValid(state,state.marks))return renderStarBattle(),setTimeout(finishStarBattle,250);renderStarBattle();}
function finishStarBattle(){if(state.kind!=='star-battle')return;const sec=Math.max(1,Math.round((Date.now()-state.startedAt)/1000)),d=state.difficulty;completeGame('star-battle','星星战役',720+state.n*35-state.hints*40-state.mistakes*30-sec,[{value:`${state.n}×${state.n}`,label:'棋盘'},{value:state.hints,label:'辅助'},{value:`${sec}s`,label:'用时'}],()=>startStarBattle(d));}
